git-branch-list(checkout_branch): Error if ID is invalid
If the given ID doesn't correspond to a branch in our database, we
should exit with an error.

diff --git a/git-branch-list b/git-branch-list
--- a/git-branch-list
+++ b/git-branch-list
@@ -56,6 +56,11 @@ function checkout_branch () {
 		fgrep "$id	" |
 		cut -d '	' -f 2)
 
+	if [ "$branch" = '' ]; then
+		echo 'branch-list: Invalid checkout ID' 1>&2
+		return 1
+	fi
+
 	git checkout "$branch"
 }
 
